const express = require('express');
const path = require('path');
const fs = require('fs');

const SERVICE_NAME = 'frontend';
const PORT = process.env.PORT || 3000;

const API_GATEWAY_PUBLIC_URL =
  process.env.API_GATEWAY_PUBLIC_URL || 'http://localhost:8080';

// Path to the discovery agent's generated correlation output.
// Can be overridden through the DISCOVERY_OUTPUT_DIR environment variable.
const DISCOVERY_OUTPUT_DIR =
  process.env.DISCOVERY_OUTPUT_DIR ||
  path.resolve(__dirname, '../../../../discovery-agent/discovery-agent/agent/output');

const CORRELATION_FILE =
  path.join(DISCOVERY_OUTPUT_DIR, 'correlation_graph.json');

const app = express();

app.use((req, res, next) => {
  const start = Date.now();

  res.on('finish', () => {
    console.log(
      `[${SERVICE_NAME}] ${req.method} ${req.originalUrl} -> ${res.statusCode} (${Date.now() - start}ms)`
    );
  });

  next();
});

app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    service: SERVICE_NAME,
    timestamp: new Date().toISOString()
  });
});

app.get('/config.js', (req, res) => {
  res.type('application/javascript');

  res.send(
    `window.API_BASE_URL = ${JSON.stringify(API_GATEWAY_PUBLIC_URL)};`
  );
});


/*
 * Infrastructure correlation endpoint.
 *
 * Reads the latest correlation_graph.json generated by
 * the discovery/correlation pipeline.
 *
 * Cache-Control: no-store is intentional because this data
 * can change between healthy/failure/recovery demonstrations.
 */
app.get('/api/correlation', (req, res) => {
  res.set('Cache-Control', 'no-store');

  try {
    if (!fs.existsSync(CORRELATION_FILE)) {
      return res.status(404).json({
        schema_version: 1,
        event_type: 'correlation_graph',
        status: 'no_data',
        message: 'No correlation data is available yet.'
      });
    }

    const raw = fs.readFileSync(
      CORRELATION_FILE,
      'utf-8'
    );

    const correlation = JSON.parse(raw);

    return res.json(correlation);

  } catch (error) {
    console.error(
      `[${SERVICE_NAME}] Failed to read correlation data:`,
      error
    );

    return res.status(500).json({
      schema_version: 1,
      event_type: 'correlation_graph',
      status: 'error',
      message: 'Failed to read correlation data.'
    });
  }
});


app.use(express.static(path.join(__dirname, 'public')));

app.listen(PORT, () => {
  console.log(
    `[${SERVICE_NAME}] listening on port ${PORT}, gateway at ${API_GATEWAY_PUBLIC_URL}`
  );

  console.log(
    `[${SERVICE_NAME}] correlation file: ${CORRELATION_FILE}`
  );
});