import { useEffect, useState } from "react";
import { api } from "../api.js";

export default function NotificationPanel({ refreshKey }) {
  const [notifications, setNotifications] = useState([]);
  const [open, setOpen] = useState(false);
  const [error, setError] = useState("");

  async function load() {
    try {
      const data = await api.listNotifications();
      setNotifications(data);
    } catch (err) {
      setError(err.message);
    }
  }

  useEffect(() => {
    load();
  }, [refreshKey]);

  // light polling so a user sees notifications generated by teammates too
  useEffect(() => {
    const interval = setInterval(load, 8000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="notification-panel">
      <button className="bell" onClick={() => setOpen((o) => !o)}>
        Notifications
        {notifications.length > 0 && <span className="count">{notifications.length}</span>}
      </button>
      {open && (
        <div className="notification-dropdown">
          {error && <div className="error">{error}</div>}
          {notifications.length === 0 ? (
            <p className="empty-state">No notifications yet.</p>
          ) : (
            <ul>
              {notifications.map((n) => (
                <li key={n.id} className={`notif notif-${n.type}`}>
                  <span className="notif-message">{n.message}</span>
                  <span className="notif-time">{new Date(n.created_at).toLocaleString()}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}
